Viettut\Entity\Core\Comment:
    type: entity
    table: viettut_comment
    repositoryClass: Viettut\Repository\Core\CommentRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
            nullable: false
        active:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: date
            nullable: true
    manyToOne:
        author:
            targetEntity: Viettut\Bundles\UserBundle\Entity\User
        course:
            targetEntity: Viettut\Entity\Core\Course
            inversedBy: comments
        tutorial:
            targetEntity: Viettut\Entity\Core\Tutorial
            inversedBy: comments
        chapter:
            targetEntity: Viettut\Entity\Core\Tutorial
            inversedBy: comments
        replyFor:
            targetEntity: Viettut\Entity\Core\Comment
            inversedBy: replies
    oneToMany:
        replies:
            targetEntity: Viettut\Entity\Core\Comment
            mappedBy: replyFor

    lifecycleCallbacks: {  }
