fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

viettut_web:
    resource: "@ViettutWebBundle/Controller/"
    type:     annotation
    prefix:   /


viettut_user_bundle:
    resource: "@ViettutUserBundle/Controller/"
    type:     annotation
    prefix:   /

viettut_api:
    resource: "@ViettutApiBundle/Resources/config/routing.yml"
    type:   rest
    prefix: /api/v1



