# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_denied_url: fos_user_security_login
    access_decision_manager:
        strategy: unanimous

    encoders:
        Viettut\Bundle\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_LECTURER: ROLE_USER
        ROLE_ADMIN:    ROLE_LECTURER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            access_denied_url: fos_user_security_login
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: home_page
                success_handler: viettut.handler.authentication_success_handler
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:
                path:   fos_user_security_logout
                target: home_page
                delete_cookies:
                    logged_in_userid:
                        path: '/'
                        domain: '.viettut.com'
            remember_me:
                lifetime: 604800
                secret: "%secret%"
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }